### ISSUE TITLE
It seems  the lib don't  support  added dynamically

### ISSUE THREAD

**Issue by zhumingu** [ApmeM/android-flowlayout#36] opened 2015-01-26 06:28 UTC
Such as the title

**Comment by ApmeM** [comment] 2015-01-26 14:27
Hi,

I am sorry, I do not understand what do you mean.
System do support dynamic elements adding.
Can you please show me your code that is not working correctly?

Thanks.

**Comment by zhumingu** [comment] 2015-01-28 02:32
ViewGroup myViewGroup = (ViewGroup) this.findViewById(R.id.myviewgroup);
        
        LayoutInflater mInflater = LayoutInflater.from(this);
        
        for(int i = 0 ; i<5;i++){
            Button button = null;
            if(i%2==0){
                button = (Button)mInflater.inflate(R.layout.button, myViewGroup, false);
                button.setText("偶数"+i);
            }else if(i%3==0){
            	button = (Button)mInflater.inflate(R.layout.button, myViewGroup, false);
                button.setText("奇数奇数"+i);
            }else{
            	button = (Button)mInflater.inflate(R.layout.button, myViewGroup, false);
                button.setText("超长的超长的超长的"+i);
            }
            
            myViewGroup.addView(button);
//................................................................

Some of its properties will not work，for example, margin.

**Comment by tunjid** [comment] 2015-05-10 21:00
I have the same issue. When added dynamically, no margins appear. All items are mashed together.

```xml
<TextView
    android:id="@+id/photo"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="left|center_vertical"
    android:layout_margin="@dimen/half_margin"
    android:padding="@dimen/half_margin"
    android:scrollbars="vertical"
    android:textColor="@color/primary" />
```

```java
    private void populateTextViews(FlowLayout flowLayout, List<Item> items) {

        TextView textView;

        try {
            for (int i = 0; i < items.size(); i++) {
                final Item item = items.get(i);

                textView = (TextView) LayoutInflater.from(flowLayout.getContext())
                        .inflate(R.layout.textview_base, flowLayout, false);

                final String text =  item.getCategory().getName();

                textView.setText(text);

                FlowLayout.LayoutParams layoutParams
                        = new FlowLayout.LayoutParams
                        (FlowLayout.LayoutParams.WRAP_CONTENT, FlowLayout.LayoutParams.WRAP_CONTENT);

                flowLayout.addView(textView, layoutParams);
            }
        }
        catch (Exception e) {
            Constants.ignoreError(e);
        }
    }
```

**Comment by tunjid** [comment] 2015-05-10 21:55
A temporary fix is wrapping the TextView in a FrameLayout. The library respects the FrameLayout for some reason. 

```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:padding="@dimen/quarter_margin">

    <TextView
        android:id="@+id/text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="left|center_vertical"
        android:background="@drawable/category_label_light"
        android:scrollbars="vertical"
        android:textColor="@color/primary" />
</FrameLayout>
```

**Comment by kitoaguila** [comment] 2015-05-12 18:54
I can confirm this issue, when adding views programmatically to the FlowLayout, margins are not consider. No matter if it is a textview or a FrameLayout.

@tunjid your solution works because you define the padding in the FrameLayout, not the margin, and paddings are respected.

**Comment by Wavesonics** [comment] 2015-05-26 21:02
Confirmed, adding views dynamically causes very broken placement of the children.

**Comment by loolooii** [comment] 2015-06-03 09:08
Just add margins dynamically to whatever view you are using in your FlowLayout:

```
final Button button = new Button(this);
FlowLayout.LayoutParams params= new FlowLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,
                            ViewGroup.LayoutParams.WRAP_CONTENT);
params.setMargins(0, 20, 20, 0);
button.setLayoutParams(params);
```

This works for me.

**Comment by julioz** [comment] 2015-06-14 23:31
I'd love to see a fix for this. Temporarily, loolooii's solution works.

**Comment by sanpark** [comment] 2015-06-25 07:10
@loolooii Thanks.Your solution works for me。

**Comment by atearsan** [comment] 2015-08-13 13:43
```java
TextView view = getLayoutInflater().inflate(R.layout.item_tag_newline, null);
FlowLayout.LayoutParams p = new FlowLayout.LayoutParams(300, 150);
p.newLine = true;
view.setLayoutParams(p);
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <TextView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:f="http://schemas.android.com/apk/res-auto"
        android:id="@+id/tag"
        android:layout_width="100dp"
        android:layout_height="34dp"
        android:layout_gravity="center"
        android:layout_margin="5dp"
        android:background="@drawable/bg_tag_orange_selector"
        android:gravity="center"
        android:padding="10dp"
        android:paddingBottom="5dp"
        android:paddingLeft="10dp"
        android:paddingRight="10dp"
        android:paddingTop="5dp"
        android:text="TAT"
        android:textColor="@drawable/textcolor_white_selector" />
</FrameLayout>
```

i write like this, is works.

**Comment by ApmeM** [comment] 2015-08-28 07:54
Hi, I have created a test for this issue (please check the latest commit).

1. I have taken comment from @tunjid and found that in latest version it works fine (and also it took margin correctly).

In your example you are rewriting layout margin that is in you inflating layout by doing this:

                FlowLayout.LayoutParams layoutParams
                        = new FlowLayout.LayoutParams
                        (FlowLayout.LayoutParams.WRAP_CONTENT, FlowLayout.LayoutParams.WRAP_CONTENT);

                flowLayout.addView(textView, layoutParams);

If you remove this layoutParams - it will take correct values from inflated layout.

2. wrapping it with one more layout will just hide the problem with overwrited parameters.

3. I still can not reproduce issue from @zhumingu as there is no examples of layout itself.

**Closed** 2015-09-18 10:23 UTC
